### ISSUE TITLE
APM - blank story content

### ISSUE THREAD

**Issue by cavis** [npr/pmp-meta#1]
(from publicmediaplatform/pmpprojectmanagement#9)

Seems there is still an issue with blank Marketplace content coming in from time to time.  Only happens with the newest content, and seems to get cleared up, eventually.  Maybe things are getting sent to the published before the content ready?

Latest example: [Marketplace for Monday, October 26, 2015](http://cav.is/s/efj5z.jpg), the [Markeplace.org link](http://www.marketplace.org/shows/marketplace/marketplace-monday-october-26-2015), and the [PMP link](https://support.pmp.io/proxy/public/docs/70454b2a-683d-43b5-88bf-4ad562089264).

Contentencoded is set to `<div class=\"barn-cleaned\"></div>`.

Calling this non-urgent, since it seems to be clearing itself up as time goes on.

**Comment by cavis** [comment]
And per @JNemic, this seems to also happen with some Splendid Table content:

> On station websites, there are a couple of stories that are basically headlines only:
> http://wunc.org/post/southside-smokehouse-grille
> http://wunc.org/post/rockaway-athletic-club

> Also found these to be the same on our test CP site.

> Here are the stories in the PMP: 
> https://support.pmp.io/search?advanced=1&searchsort=date&guid=4155b95d-d383-437d-83d2-1e062c732400
> https://support.pmp.io/search?advanced=1&searchsort=date&guid=913661cc-d42f-4903-8260-39de1cb83350

**Comment by dgorsline** [comment]
Migrated from http://jira.npr.org/browse/DIG-4093
