### ISSUE TITLE
PBS - Property/Series links

### ISSUE THREAD

**Issue by cavis** [npr/pmp-meta#10]
(from publicmediaplatform/pmpprojectmanagement#34)

Create Property and Series docs for PBS content.

**Comment by cavis** [comment]
Per the old comment thread, Tobin says:

> Unfortunately guys, this is a limitation of the COVE API, where I'm trying from.

> E.g.

> http://api.pbs.org/cove/v1/videos/?filter_title=Downton%20Abbey

> This will return Downton Abbey vids, but no trace of its property. We're in process of fixing the COVE API and our whole data model at PBSd to repair this major shortcoming.

Then Ryan says:

> What about the `filter_program` parameter? If you knew the ID of the Downton Abbey program, you could make a query that was guaranteed to only return videos in that program. And then it's just a matter of maintaining that `pbs_program_id` => `pmp_collection_guids` mapping.

**Comment by dgorsline** [comment]
Migrated to http://jira.npr.org/browse/DIG-4084
