### ISSUE TITLE
PBS - Story containers for media

### ISSUE THREAD

**Issue by cavis** [npr/pmp-meta#11]
(from publicmediaplatform/pmpprojectmanagement#38)

Although using `profile=story` docs is not a requirement (see the [forum thread](https://discuss.pmp.io/t/vote-story-profile-as-required-base-document-for-all-pmp-documents/80)), I still see this as a barrier to adoption of PBS content.

**Comment by dgorsline** [comment]
Migrated to http://jira.npr.org/browse/DIG-4083
