### ISSUE TITLE
PBS - Video doc issues

### ISSUE THREAD

**Issue by cavis** [npr/pmp-meta#12]
(partially from publicmediaplatform/pmpprojectmanagement#35)

Still seeing a few data issues on PBS `profile=video` docs:
- [ ] Published date not matching the source video on pbs.org
- [ ] Duplicate / redundant / blank tags (I'd remove the `PBS` and `""` tags)

Also wondering where `duration` should be stored, since you're using `attributes.contentencoded` instead of `links.enclosure`.

**Comment by dgorsline** [comment]
Migtated to http://jira.npr.org/browse/DIG-4082
