### ISSUE TITLE
PRI - Published date on stories

### ISSUE THREAD

**Issue by cavis** [npr/pmp-meta#15]
(from publicmediaplatform/pmpprojectmanagement#43)

Looks like PMP published dates are still a bit off from their source articles.

In fact, with this [The World story](https://support.pmp.io/search?searchsort=date&guid=7d8fa68a-f867-4e1a-8b30-dd5311914bec), it looks like it's defaulting the `attributes.published` to when it was pushed to the PMP (October 28th).  But the [PRI.org article](http://www.pri.org/stories/2008-08-04/reporter-visits-family-village-site-nazi-attack) is displaying August 2008.

**Comment by dgorsline** [comment]
Migrated to http://jira.npr.org/browse/DIG-4079
