### ISSUE TITLE
NPR - User image and title

### ISSUE THREAD

**Issue by cavis** [npr/pmp-meta#2]
(from publicmediaplatform/pmpprojectmanagement#19)

For attribution purposes, the NPR user should probably get an attached image item.

And maybe change the title from "NPR Digital Media" to just "NPR" or "National Public Radio". Since that can (and will) get displayed somewhere.

https://support.pmp.io/proxy/public/docs/6140faf0-fb45-4a95-859a-070037fafa01

**Comment by dgorsline** [comment]
Migrated to http://jira.npr.org/browse/DIG-4092
