### ISSUE TITLE
PRI - Relative alternate links

### ISSUE THREAD

**Issue by cavis** [npr/pmp-meta#26]
(from publicmediaplatform/pmpprojectmanagement#65)

Some older PRI docs have relative `links.alternate`.  Example: https://support.pmp.io/proxy/public/docs/9ab0253d-0b69-427e-bb08-1d848e4cac32

Should clean these up eventually.

(See the old ticket for a SQL statement to grab all the 500-ish guids).

**Comment by dgorsline** [comment]
http://jira.npr.org/browse/DIG-4066
