### ISSUE TITLE
NPR - Lack of "rich media" in contentencoded

### ISSUE THREAD

**Issue by cavis** [npr/pmp-meta#27]
(from publicmediaplatform/pmpprojectmanagement#67)

Currently, NPR stories are imported to the PMP via a "public" StoryAPI key.  Consequently, any station-restricted rich media (videos, iframe-graphs, etc) don't make it into the PMP.

For example:
- http://www.npr.org/blogs/money/2014/10/02/349863761/40-years-of-income-inequality-in-america-in-graphs
- https://support.pmp.io/proxy/public/docs/402d98df-f1d9-481f-9b28-a1c30de35744

This can sometimes result in some funny text content referring to media that isn't there.  Capturing this limitation here.

**Comment by dgorsline** [comment]
http://jira.npr.org/browse/DIG-4065
