### ISSUE TITLE
NPR - Blank href for embargoed audio

### ISSUE THREAD

**Issue by cavis** [npr/pmp-meta#28]
(from publicmediaplatform/pmpprojectmanagement#72)

> While testing something else, I came across a recent NPR story where the audio wasn't working.
> 
> Turns out, the audio enclosure had a blank href. And although the json-schema does allow that, I've been considering implementing more stringent regex validations on some of these fields to disallow blank strings.
> 
> Going to the original story, looks like the audio was embargoed.
> 
> Ideally, there would be a better way to handle embargoed docs/media. Perhaps through the valid.from date (assuming all clients respect it) or by not creating the audio doc until the media is available.

**Comment by dgorsline** [comment]
http://jira.npr.org/browse/DIG-4064
