### ISSUE TITLE
PRI - Alternate links to admin.pri.org

### ISSUE THREAD

**Issue by cavis** [npr/pmp-meta#29]
(from publicmediaplatform/pmpprojectmanagement#85)

For whatever reason, all recent PRI stories have alternate links pointing to "admin.pri.org". Seems to have started between May 6th and May 12th. Before that, links all go to "www.pri.org".

Most of them still seem to work (admin seems to be alias for "www.pri.org"). But some, like this #ExplainTheSun story require a login. Although it looks like the "www" version of that one also requires a login.

**Comment by dgorsline** [comment]
http://jira.npr.org/browse/DIG-4063
