### ISSUE TITLE
NPR - Published dates don't line up with source article

### ISSUE THREAD

**Issue by cavis** [npr/pmp-meta#3]
(from publicmediaplatform/pmpprojectmanagement#20)

NPR stories have an `attributes.published` timestamp which does not match what's displayed on the original article.  Example:
- A [PMP Story](https://support.pmp.io/proxy/public/docs/df1dc8d8-7530-406c-83aa-31e5440c020a) - published `2015-10-27T15:10:00+00:00`
- The [NPR.org link](http://www.npr.org/sections/npr-history-dept/2015/10/27/452089384/a-very-weird-photo-of-ulysses-s-grant?ft=nprml&f=452089384) - shows `OCTOBER 27, 201511:03 AM ET`

Per the previous discussion, this is because NPR is setting the "story last modified" date in the published field.  For display purposes, this should probably be updated to be the "original published date".

**Comment by dgorsline** [comment]
Migrated to http://jira.npr.org/browse/DIG-4091
