### ISSUE TITLE
PRI - Cleanup broken audio links

### ISSUE THREAD

**Issue by cavis** [npr/pmp-meta#30]
(from publicmediaplatform/pmpprojectmanagement#86)

At one point, there were some broken audio links coming into the PMP. They started with http://cdn.pri.org/pts/redirect.mp3/. Looks like there are 343 of these still around, mostly from Fall 2014. (Although there are a few as recent as May 2015).

This is a note to go back and clean those up, at some point. Here's the list -> https://gist.github.com/cavis/e3e8d51344bc07bc5c74

**Comment by dgorsline** [comment]
Migrated to http://jira.npr.org/browse/DIG-4062
