### ISSUE TITLE
PRI - Lead video field missing

### ISSUE THREAD

**Issue by cavis** [npr/pmp-meta#31]
(from publicmediaplatform/pmpprojectmanagement#88)

The [story out on PRI.org](http://www.pri.org/stories/2015-04-13/twin-sisters-follow-their-dads-buena-vista-social-club-roots-afro-caribbean-music) does include a big "featured video" at the top.

But [in the PMP](https://support.pmp.io/search?advanced=1&text=%22Twin%20sisters%20follow%20their%20dad%27s%20Buena%20Vista%20Social%20Club%20roots%20into%20Afro-Caribbean%20music%22&profile=story), this is just a Story+Audio.  (And that 2nd video is embedded into the `contentencoded` of the Story, but not the 1st one).

According to @brandonhundt:

> I found the issue. In our CMS we have a field that can house the lead image or lead video. It is mapped directly to the PMP image doc. So if a video is used in the lede its not getting over to PMP. We will add this to our internal list of PMP to-dos to make sure if a video is upload to that field it gets mapped to the right place and a fallback thumbnail is sent sent to PMP as well.

**Comment by dgorsline** [comment]
http://jira.npr.org/browse/DIG-4061
