### ISSUE TITLE
APM - Description same as teaser

### ISSUE THREAD

**Issue by cavis** [npr/pmp-meta#34]
(from publicmediaplatform/pmpprojectmanagement#98)

It looks like your stories have identical `attributes.teaser` and `attributes.description` fields.  For example... [this Marketplace story](https://support.pmp.io/proxy/public/docs/0349a5f7-241b-40ef-8422-09d7b3f5bb91).

Per the [best practices](https://support.pmp.io/docs#dictionary-story), `attributes.description` should actually be the html-tagged-stripped version of `contentencoded`.

**Comment by dgorsline** [comment]
Migrated to http://jira.npr.org/browse/DIG-4058
