### ISSUE TITLE
NPRDS - Core Publisher broken images

### ISSUE THREAD

**Issue by cavis** [npr/pmp-meta#35]
(from publicmediaplatform/pmpprojectmanagement#74)

You'll have to go read the old issue for history/screenshots, but to sum it up: many images in CP are broken.

**Comment by cavis** [comment]
Also see publicmediaplatform/pmpprojectmanagement#87.

**Comment by dgorsline** [comment]
Migrated to http://jira.npr.org/browse/DIG-4094
