### ISSUE TITLE
NPRDS - Marketplace stories missing audio

### ISSUE THREAD

**Issue by cavis** [npr/pmp-meta#36]
(from publicmediaplatform/pmpprojectmanagement#81)

> Title says it all: for some stories, no audio appears. Ryan did a bit of checking in the PMP and all looks good there. 
> 
> Example stories:
> http://pmptest.drupal.publicbroadcasting.net/post/vacation-all-i-ever-wanted-i-dont-take-one
> http://www.marketplace.org/topics/business/vacation-all-i-ever-wanted-i-dont-take-one
> https://support.pmp.io/search?advanced=1&guid=f0767ef6-020d-4aa1-8fad-77df25408182
> 
> http://pmptest.drupal.publicbroadcasting.net/post/bridging-edtech-gap-oyler-school-home
> http://www.marketplace.org/topics/education/one-school-one-year/bridging-edtech-gap-oyler-school-home
> https://support.pmp.io/search?advanced=1&guid=48e8ad30-afb0-4b5d-8555-8c81d468e5aa

**Comment by dgorsline** [comment]
http://jira.npr.org/browse/DIG-4057
