### ISSUE TITLE
NPRDS - Marketplace video not showing in Firefox

### ISSUE THREAD

**Issue by cavis** [npr/pmp-meta#37]
The video in the story (midway down the page):
http://www.marketplace.org/topics/education/one-school-one-year/bridging-edtech-gap-oyler-school-home

Does not show up on the corresponding CP page in Firefox:
(from publicmediaplatform/pmpprojectmanagement#80)

http://pmptest.drupal.publicbroadcasting.net/post/bridging-edtech-gap-oyler-school-home
(It does appear in Chrome, but smaller than the original.)

Video on Marketplace site (in Firefox):
![video on marketplace site](https://cloud.githubusercontent.com/assets/4427754/8186649/82f295f4-1419-11e5-83de-4a0a9c1cd7ed.png)

No video on CP site (in Firefox):
![firefox_no_video](https://cloud.githubusercontent.com/assets/4427754/8186650/855afd90-1419-11e5-9389-0ee1650f0092.png)

Small video on CP site (in Chrome): 
![cp_video_chrome](https://cloud.githubusercontent.com/assets/4427754/8186681/b7873f2c-1419-11e5-9431-ee6836bab4a1.png)

Story in PMP: https://support.pmp.io/search?advanced=1&guid=48e8ad30-afb0-4b5d-8555-8c81d468e5aa

**Comment by dgorsline** [comment]
Migrated to http://jira.npr.org/browse/DIG-4056
