### ISSUE TITLE
NPRDS - Not showing tables

### ISSUE THREAD

**Issue by cavis** [npr/pmp-meta#38]
(from publicmediaplatform/pmpprojectmanagement#76)

Should CP should be whitelisting all table-ish tags: < table> < thead> < tbody> < tr> < th> < td>?
http://delmarvapublicradio.net/post/pols-deride-uber-they-also-ride-uber-lot-documents-show
(2/3 of the way down, code for a table is visible on page)

Dave had mentioned that this is probably due to the way CP handles PMP content -- basically making stories into CP posts, and CP strictly limits what users can include in posts. 

![fireshot screen capture 086 - pols deride uber_ they also ride uber_ a lot documents show_ i delmarva public radio - delmarvapublicradio_net_post_pols-deride-uber-they-also-ride-uber-lot-documents-show](https://cloud.githubusercontent.com/assets/4427754/7837484/40b124c2-0455-11e5-81d2-6bb0266b9b87.png)

**Comment by dgorsline** [comment]
http://jira.npr.org/browse/DIG-4055
