### ISSUE TITLE
NPRDS: long image captions causing errors?

### ISSUE THREAD

**Issue by JNemic** [npr/pmp-meta#39]
Andrea at Side Effects Public Media wrote me about an error they were getting when trying to pull this story: 169e08c9-13ab-4d72-8e3e-c16286b6b68b

I tried on our CP test site and got the following errors as well:
-    The specified file temporary://fileb2NAOW could not be copied, because the destination directory is not properly configured. This may be caused by a problem with file or directory permissions. More information is available in the system log.
-    http://www.marketplace.org/sites/default/files/styles/primary-image-610x340/public/GettyImages-495382986.jpg?itok=PxRquhVa could not be saved to sites/shared/pmp/201511/5beeaccf-4938-4e9a-89ba-e342c763f136.jpg.
-    PDOException: SQLSTATE[22001]: String data, right truncated: 1406 Data too long for column 'field_image_caption_value' at row 1: INSERT INTO {field_data_field_image_caption} (entity_type, entity_id, revision_id, bundle, delta, language, field_image_caption_value, field_image_caption_format) VALUES (:db_insert_placeholder_0, :db_insert_placeholder_1, :db_insert_placeholder_2, :db_insert_placeholder_3, :db_insert_placeholder_4, :db_insert_placeholder_5, :db_insert_placeholder_6, :db_insert_placeholder_7); Array ( [:db_insert_placeholder_0] => file [:db_insert_placeholder_1] => 10855 [:db_insert_placeholder_2] => 10855 [:db_insert_placeholder_3] => image [:db_insert_placeholder_4] => 0 [:db_insert_placeholder_5] => und [:db_insert_placeholder_6] => Martha Lucia (L) sits with Rudy Figueroa, an insurance agent from Sunshine Life and Health Advisors, as she picks an insurance plan available in the third year of the Affordable Care Act at a store setup in the Mall of the Americas on November 2, 2015 in Miami, Florida. [:db_insert_placeholder_7] => 2 ) in field_sql_storage_field_storage_write() (line 448 of /var/www/drupal7-2015-RYLOSHOTFIXONE/modules/field/modules/field_sql_storage/field_sql_storage.module).

I talked with Ryan and he thought that there may be an image caption limit in Core Publisher that is causing the error. 

---

Hey Jeff,

When trying to pull this story, I got the following error. I tried it twice a couple of hours apart.

·         The specified file temporary://fileVq0TfT could not be copied, because the destination directory is not properly configured. This may be caused by a problem with file or directory permissions. More information is available in the system log.

·         http://www.marketplace.org/sites/default/files/styles/primary-image-610x340/public/GettyImages-495382986.jpg?itok=PxRquhVa could not be saved to sites/shared/pmp/201511/5beeaccf-4938-4e9a-89ba-e342c763f136.jpg.

Thanks,
Andrea

**Comment by dgorsline** [comment]
Migrated to http://jira.npr.org/browse/DIG-4054
