### ISSUE TITLE
NPR - Property/Series links

### ISSUE THREAD

**Issue by cavis** [npr/pmp-meta#5]
(from publicmediaplatform/pmpprojectmanagement#24)

Create Property and Series docs for NPR content.  Probably mapping out of the "Programs / Blogs / Series / etc" from the Story API.

**Comment by scottsmith130** [comment]
FWIW, we are aiming to begin having program data available with our next code release.  There will be property docs created for programs and stories will be linking to them.

**Comment by cavis** [comment]
Yeah, that's what I'd heard.  Also, do you know if you're doing any hierarchy with Property/Series?  Or just the Property for now?

(I seem to recall "Programs / Series" in the Story API not quite being a 1-to-1 mapping to the PMP "Property / Series" concept).

**Comment by scottsmith130** [comment]
Just programs for now.  And just story-to-program mappings - we haven't even touched on mapping program episodes to stories yet (which is yet another level of hierarchy we have).  

We can probably do other aggregations at some point.  I don't really remember much about the Property/Series concept, but I'm not sure I see why we can't just map NPR series to docs that use the "series" profile.  I think these aggs will fall into place in the PMP realm much easier once we start thinking about how we are going to model them as cdocs in our own environment.

**Comment by cavis** [comment]
@scottsmith130 it looks like you're now pushing Properties to production.  But the support searcher still isn't picking up the change on the attribution side (it still attributes it to "NPR Digital Media", the creator, rather than a collection link).

![image](https://cloud.githubusercontent.com/assets/1410587/11196906/3912cd74-8c77-11e5-9e18-0aae2300a2c2.png)

This seems to be due to the lack of a `link.rels = "urn:collectiondoc:collection:property"`, so the client can tell that collection link is to a Property.  (See issue #7).

Any chance we can get that change in quick?

**Comment by scottsmith130** [comment]
Not without re-pushing all of our content again.  Which last time took about 12-15 hours.

Probably my fault.  I didn't realize we had to use a link.rels for this.  I'm guessing that's just something the support.pmp.io site is looking for though. 

 To be honest, I'm not really a fan of something like this particular rels URN - it basically means I can't ever change the profile of the document being linked without also changing the rels URN everywhere it is linked.  It forces documents to be a bit too coupled.  I see why a client might find it valuable, but it breaks the hypermedia concept a bit.  Tying link relations to profiles is not a good idea in my opinion.

**Comment by cavis** [comment]
To me, this is more of a practical issue around attribution.  If I know which relationship-subtype I'm looking for (the Property to this Story), it's an efficient way to find the doc(s) I'm looking for without unnecessary fetches.

If a story has 27 `links.collection` ... how do I know which one of them is the "Program title"?  At minimum, I would have to fetch all 27 of them to find out which have `profile=property`.  And if there are multiple property collections?

**Comment by cavis** [comment]
Also, I just re-read your comment.  And I guess I don't view this as "profile" coupling - the profile and the relType just happen to share the same name in this case.

If you changed the profile type of your collections down the road, I would probably leave the `rels` alone, as the collection still represents the "Property" the story belongs to, and should be attributed to.

**Comment by scottsmith130** [comment]
What can I say, I'm a hypermedia purist.  I hate the secondary relations because it makes the hypermedia not so pure.  In a perfect world, the client would just follow all the links with infinite speed and capacity and we probably wouldn't even need primary link relations.  

But yes, here on Earth link relations are practical.  And I will say that I'd prefer using secondary link relations over titles.  I hope no one would argue the point that putting the program title into the link to the property is coupling.  I'd hate to have to change the program title ever in such a case (and have to republish all those docs that link to it).

**Comment by scottsmith130** [comment]
Getting back to the issue at hand, I'll suggest to the team we update the docs again to use the link relation.

**Comment by dgorsline** [comment]
Migrated to http://jira.npr.org/browse/DIG-4089
