### ISSUE TITLE
NPR - Missing rels on item/collection links

### ISSUE THREAD

**Issue by cavis** [npr/pmp-meta#7]
(from publicmediaplatform/pmpprojectmanagement#27)

Should set some `link.rels` for:
- `links.item` - https://support.pmp.io/docs#best-practices-item-links
- `links.collection` - https://support.pmp.io/docs#best-practices-collection-links

**Comment by dgorsline** [comment]
Migrated to http://jira.npr.org/browse/DIG-4087
